<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-11-07 02:49
=======
# Generated by Django 5.2.7 on 2025-11-12 01:29
>>>>>>> fb2d15f825c06cf4618c5fbe78cc2d2f6f22ce9e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
