# Generated by Django 5.2.7 on 2025-11-26 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_ticketmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticketmessage',
            new_name='system_tick_ticket__3fa05b_idx',
            old_name='system_ticketmessage_ticket_idx',
        ),
    ]
