BEGIN;
--
-- Create model OrderStatusHistory
--
CREATE TABLE "orders_orderstatushistory" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "old_status" varchar(50) NOT NULL, "new_status" varchar(50) NOT NULL, "changed_at" timestamp with time zone NOT NULL, "reason" varchar(255) NOT NULL, "changed_by_id" bigint NULL, "order_id" bigint NOT NULL);
ALTER TABLE "orders_orderstatushistory" ADD CONSTRAINT "orders_orderstatushi_changed_by_id_d823a516_fk_users_use" FOREIGN KEY ("changed_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orders_orderstatushistory" ADD CONSTRAINT "orders_orderstatushistory_order_id_bf09a0e1_fk_orders_order_id" FOREIGN KEY ("order_id") REFERENCES "orders_order" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "orders_orderstatushistory_changed_by_id_d823a516" ON "orders_orderstatushistory" ("changed_by_id");
CREATE INDEX "orders_orderstatushistory_order_id_bf09a0e1" ON "orders_orderstatushistory" ("order_id");
CREATE INDEX "orders_orde_order_i_f43086_idx" ON "orders_orderstatushistory" ("order_id");
CREATE INDEX "orders_orde_new_sta_58c5a2_idx" ON "orders_orderstatushistory" ("new_status");
COMMIT;
