BEGIN;
--
-- Create model ProductVariant
--
CREATE TABLE "products_productvariant" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "sku" varchar(64) NOT NULL UNIQUE, "price" numeric(12, 2) NOT NULL, "stock" integer NOT NULL CHECK ("stock" >= 0), "color" varchar(50) NOT NULL, "storage" varchar(50) NOT NULL, "active" boolean NOT NULL, "product_id" bigint NOT NULL);
--
-- Create model ProductImage
--
CREATE TABLE "products_productimage" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "url" varchar(500) NOT NULL, "is_primary" boolean NOT NULL, "sort_order" integer NOT NULL, "created_at" timestamp with time zone NOT NULL, "product_id" bigint NOT NULL, "variant_id" bigint NULL);
--
-- Create model ProductSpec
--
CREATE TABLE "products_productspec" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "key" varchar(100) NOT NULL, "value" varchar(255) NOT NULL, "unit" varchar(20) NOT NULL, "display_order" integer NOT NULL, "searchable" boolean NOT NULL, "product_id" bigint NOT NULL);
--
-- Create index products_pr_product_cee51f_idx on field(s) product of model productvariant
--
CREATE INDEX "products_pr_product_cee51f_idx" ON "products_productvariant" ("product_id");
--
-- Create index products_pr_active_5aad7f_idx on field(s) active of model productvariant
--
CREATE INDEX "products_pr_active_5aad7f_idx" ON "products_productvariant" ("active");
--
-- Create index products_pr_product_3d7874_idx on field(s) product of model productimage
--
CREATE INDEX "products_pr_product_3d7874_idx" ON "products_productimage" ("product_id");
--
-- Create index products_pr_variant_4f60d9_idx on field(s) variant of model productimage
--
CREATE INDEX "products_pr_variant_4f60d9_idx" ON "products_productimage" ("variant_id");
--
-- Create index products_pr_is_prim_b891de_idx on field(s) is_primary of model productimage
--
CREATE INDEX "products_pr_is_prim_b891de_idx" ON "products_productimage" ("is_primary");
ALTER TABLE "products_productvariant" ADD CONSTRAINT "products_productvari_product_id_d9c22902_fk_products_" FOREIGN KEY ("product_id") REFERENCES "products_product" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "products_productvariant_sku_1b692018_like" ON "products_productvariant" ("sku" varchar_pattern_ops);
CREATE INDEX "products_productvariant_product_id_d9c22902" ON "products_productvariant" ("product_id");
ALTER TABLE "products_productimage" ADD CONSTRAINT "products_productimag_product_id_e747596a_fk_products_" FOREIGN KEY ("product_id") REFERENCES "products_product" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "products_productimage" ADD CONSTRAINT "products_productimag_variant_id_bf70ade8_fk_products_" FOREIGN KEY ("variant_id") REFERENCES "products_productvariant" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "products_productimage_product_id_e747596a" ON "products_productimage" ("product_id");
CREATE INDEX "products_productimage_variant_id_bf70ade8" ON "products_productimage" ("variant_id");
ALTER TABLE "products_productspec" ADD CONSTRAINT "products_productspec_product_id_key_802990ea_uniq" UNIQUE ("product_id", "key");
ALTER TABLE "products_productspec" ADD CONSTRAINT "products_productspec_product_id_1df3a992_fk_products_product_id" FOREIGN KEY ("product_id") REFERENCES "products_product" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "products_productspec_product_id_1df3a992" ON "products_productspec" ("product_id");
CREATE INDEX "products_pr_product_ee030a_idx" ON "products_productspec" ("product_id", "key");
COMMIT;
