BEGIN;
--
-- Create model Log
--
CREATE TABLE "system_log" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "level" varchar(50) NOT NULL, "message" text NOT NULL, "created_at" timestamp with time zone NOT NULL);
--
-- Create model Policy
--
CREATE TABLE "system_policy" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "condition" varchar(255) NOT NULL, "action" varchar(255) NOT NULL, "active" boolean NOT NULL);
--
-- Create model SystemSetting
--
CREATE TABLE "system_systemsetting" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "key" varchar(100) NOT NULL UNIQUE, "value" varchar(255) NOT NULL, "description" text NOT NULL);
--
-- Create model Audit
--
CREATE TABLE "system_audit" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action" varchar(255) NOT NULL, "created_at" timestamp with time zone NOT NULL, "details" text NOT NULL, "user_id" bigint NULL);
--
-- Create model SupportTicket
--
CREATE TABLE "system_supportticket" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "subject" varchar(200) NOT NULL, "message" text NOT NULL, "status" varchar(50) NOT NULL, "priority" varchar(20) NOT NULL, "created_at" timestamp with time zone NOT NULL, "closed_at" timestamp with time zone NULL, "order_id" bigint NULL, "product_id" bigint NULL, "user_id" bigint NOT NULL);
CREATE INDEX "system_systemsetting_key_0dfb2f94_like" ON "system_systemsetting" ("key" varchar_pattern_ops);
ALTER TABLE "system_audit" ADD CONSTRAINT "system_audit_user_id_65ffc972_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "system_audit_user_id_65ffc972" ON "system_audit" ("user_id");
ALTER TABLE "system_supportticket" ADD CONSTRAINT "system_supportticket_order_id_55a7b4cc_fk_orders_order_id" FOREIGN KEY ("order_id") REFERENCES "orders_order" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "system_supportticket" ADD CONSTRAINT "system_supportticket_product_id_dfcc3886_fk_products_product_id" FOREIGN KEY ("product_id") REFERENCES "products_product" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "system_supportticket" ADD CONSTRAINT "system_supportticket_user_id_17da0aac_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "system_supportticket_order_id_55a7b4cc" ON "system_supportticket" ("order_id");
CREATE INDEX "system_supportticket_product_id_dfcc3886" ON "system_supportticket" ("product_id");
CREATE INDEX "system_supportticket_user_id_17da0aac" ON "system_supportticket" ("user_id");
CREATE INDEX "system_supp_user_id_8a479a_idx" ON "system_supportticket" ("user_id", "status");
CREATE INDEX "system_supp_order_i_f124d7_idx" ON "system_supportticket" ("order_id");
COMMIT;
