# Generated by Django 5.2.7 on 2025-11-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_variant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderdiscount',
            unique_together={('order', 'discount')},
        ),
    ]
