# Generated by Django 5.2.7 on 2025-11-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_active'),
        ('orders', '0006_alter_orderdiscount_unique_together'),
    ]

    operations = [
    ]
